#NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")

resources:
  repositories:
    - repository: self
      trigger: none

variables:
  azureServiceConnection: 'Tema-sc'
  resourceGroup: 'Eshop-wus-rg'
  location: 'westus'
  subscriptionId: '24e9df87-f699-49ca-ad4e-eaf026d4fbf8'

stages:
- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy App Service using Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureServiceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroup)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: 'infra/webapp-docker.bicep'
        deploymentMode: 'Incremental'
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Add Role Assignment using Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureServiceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroup)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: 'infra/webapp-to-acr-roleassignment.bicep'
        deploymentMode: 'Incremental'
